// =============================================================
// Habla Guanaca — Pack 04: A otro nivel (Mastery)
// 10 advanced lessons: versatile verbs, tricky grammar & storytelling
// L31–L40. No embedded audio — uses the (de-lisped) TTS fallback.
// =============================================================
(function() {
  window.HABLA_PACKS = window.HABLA_PACKS || [];

  const lessons = [
    {
      id: "L31", title: "Faltar", subtitle: "What's Missing", icon: "🧩",
      description: "One verb for lacking, missing someone, and 'how much longer'", estimatedMinutes: 14,
      dialogue: {
        context: "Friends are waiting on someone who's running late.",
        lines: [
          { speaker: "A", textEs: "¿Cuánto te falta para llegar?", textEn: "How much longer till you get here?" },
          { speaker: "B", textEs: "Me falta poco, ya voy en camino.", textEn: "Almost there, I'm on my way." },
          { speaker: "A", textEs: "Apurate, que sin vos no es lo mismo. ¡Nos hacés falta!", textEn: "Hurry, it's not the same without you. We miss you!" },
          { speaker: "B", textEs: "Aww, ya casi. Solo me faltaba pasar comprando hielo.", textEn: "Aww, almost. I just had to stop to buy ice." },
        ],
      },
      priorReview: [
        { id: "L04-13", promptEn: "Can you spare a moment? (informal)", targetEs: "¿Me regalás el tiempo?", standardEs: "¿Me regalas el tiempo?", pronunciation: "meh rreh-gah-LAHS ehl tee-EHM-poh", culturalNote: "Literally 'gift me the time' — using 'regalar' instead of 'dar' is distinctly Central American." },
        { id: "L21-11", promptEn: "Listen, here's the thing...", targetEs: "Fíjate que...", standardEs: "Fíjate que...", pronunciation: "FEE-hah-teh keh", culturalNote: "Classic Salvadoran story-opener and excuse-maker. Means 'picture this' or 'the thing is...'" },
      ],
      newItems: [
        { id: "L31-01", promptEn: "I miss you (vos)", targetEs: "Me hacés falta", standardEs: "Me haces falta", pronunciation: "meh ah-SEHS FAHL-tah", culturalNote: "Literally 'you make lack to me' — the warm, relational way to say you miss someone. SV also says 'te extraño'" },
        { id: "L31-02", promptEn: "I'm short on money", targetEs: "Me falta dinero", pronunciation: "meh FAHL-tah dee-NEH-roh", culturalNote: "With faltar, the thing you lack is the subject — it 'is lacking to me'" },
        { id: "L31-03", promptEn: "How much longer? / How far?", targetEs: "¿Cuánto falta?", pronunciation: "KWAHN-toh FAHL-tah", culturalNote: "Works for time left or distance left" },
        { id: "L31-04", promptEn: "Almost there / Not much left", targetEs: "Falta poco", pronunciation: "FAHL-tah POH-koh" },
        { id: "L31-05", promptEn: "I'm two short / I need two more", targetEs: "Me faltan dos", pronunciation: "meh FAHL-tahn dohs", culturalNote: "Plural thing lacking (dos) → faltan, not falta" },
        { id: "L31-06", promptEn: "He/she skipped class", targetEs: "Faltó a clase", pronunciation: "fahl-TOH ah KLAH-seh", culturalNote: "faltar a = to not show up to an obligation (class, work, a date)" },
        { id: "L31-07", promptEn: "But of course! / Don't mention it", targetEs: "No faltaba más", pronunciation: "noh fahl-TAH-bah MAHS", culturalNote: "Gracious reply to thanks or a favor — 'it's the very least'" },
        { id: "L31-08", promptEn: "What do you still need?", targetEs: "¿Qué te falta?", pronunciation: "keh teh FAHL-tah" },
        { id: "L31-09", promptEn: "I need to rest", targetEs: "Me hace falta descansar", pronunciation: "meh AH-seh FAHL-tah dehs-kahn-SAHR", culturalNote: "hacer falta + verb = to need to do something" },
        { id: "L31-10", promptEn: "There's a week to go", targetEs: "Falta una semana", pronunciation: "FAHL-tah OO-nah seh-MAH-nah" },
        { id: "L31-11", promptEn: "That's the last thing I needed! (sarcastic)", targetEs: "¡Lo que faltaba!", pronunciation: "loh keh fahl-TAH-bah", culturalNote: "Ironic — muttered when one more bad thing piles on" },
        { id: "L31-12", promptEn: "Without fail / For sure", targetEs: "Sin falta", pronunciation: "seen FAHL-tah", culturalNote: "'Mañana sin falta' = tomorrow for sure, no excuses" },
        { id: "L31-13", promptEn: "I could use your help", targetEs: "Me haría falta tu ayuda", pronunciation: "meh ah-REE-ah FAHL-tah too ah-YOO-dah" },
      ],
    },
    {
      id: "L32", title: "Contar", subtitle: "Count, Tell & Rely On", icon: "🔢",
      description: "Counting, telling stories, and counting on people — one verb", estimatedMinutes: 14,
      dialogue: {
        context: "Two friends catching up on the street.",
        lines: [
          { speaker: "A", textEs: "¡Maje! ¿Qué me contás?", textEn: "Dude! What's up?" },
          { speaker: "B", textEs: "Uy, te cuento que conseguí trabajo nuevo.", textEn: "Oh, let me tell you, I got a new job." },
          { speaker: "A", textEs: "¡No jodás! Qué chivo. Contá con mi ayuda para la mudanza.", textEn: "No way! Awesome. Count on me for the move." },
          { speaker: "B", textEs: "Gracias, maje. Sabía que podía contar con vos.", textEn: "Thanks, dude. I knew I could count on you." },
        ],
      },
      priorReview: [
        { id: "L21-05", promptEn: "I heard that...", targetEs: "Me dijeron que...", pronunciation: "meh dee-HEH-rohn keh", culturalNote: "'They told me that...' — classic gossip opener, keeps your source anonymous" },
        { id: "L31-01", promptEn: "I miss you (vos)", targetEs: "Me hacés falta", standardEs: "Me haces falta", pronunciation: "meh ah-SEHS FAHL-tah" },
      ],
      newItems: [
        { id: "L32-01", promptEn: "What's up? / What's new? (vos)", targetEs: "¿Qué me contás?", standardEs: "¿Qué me cuentas?", pronunciation: "keh meh kohn-TAHS", culturalNote: "Literally 'what do you tell me?' — a super common voseo greeting" },
        { id: "L32-02", promptEn: "Let me tell you that...", targetEs: "Te cuento que...", pronunciation: "teh KWEHN-toh keh", culturalNote: "Opener for news or a story" },
        { id: "L32-03", promptEn: "Count on me (vos)", targetEs: "Contá conmigo", standardEs: "Cuenta conmigo", pronunciation: "kohn-TAH kohn-MEE-goh" },
        { id: "L32-04", promptEn: "I can count on you (vos)", targetEs: "Puedo contar con vos", standardEs: "Puedo contar contigo", pronunciation: "PWEH-doh kohn-TAHR kohn vohs" },
        { id: "L32-05", promptEn: "to count (numbers)", targetEs: "contar", pronunciation: "kohn-TAHR", culturalNote: "Same verb that counts numbers also tells stories — context tells them apart" },
        { id: "L32-06", promptEn: "I was told that...", targetEs: "Me contaron que...", pronunciation: "meh kohn-TAH-rohn keh", culturalNote: "Cousin of 'me dijeron que' — secondhand news" },
        { id: "L32-07", promptEn: "Did I tell you that...?", targetEs: "¿Te conté que...?", pronunciation: "teh kohn-TEH keh" },
        { id: "L32-08", promptEn: "Tell me everything", targetEs: "Contame todo", standardEs: "Cuéntame todo", pronunciation: "kohn-TAH-meh TOH-doh", culturalNote: "Vos command: contame. Usted: cuénteme" },
        { id: "L32-09", promptEn: "Don't tell me lies! (vos)", targetEs: "¡No me contés mentiras!", standardEs: "¡No me cuentes mentiras!", pronunciation: "noh meh kohn-TEHS mehn-TEE-rahs" },
        { id: "L32-10", promptEn: "That doesn't count", targetEs: "Eso no cuenta", pronunciation: "EH-soh noh KWEHN-tah", culturalNote: "Here 'cuenta' means 'counts / matters'" },
        { id: "L32-11", promptEn: "At the end of the day", targetEs: "A fin de cuentas", pronunciation: "ah feen deh KWEHN-tahs", culturalNote: "Wrapping up an argument — 'when all's said and done'" },
        { id: "L32-12", promptEn: "I lost count", targetEs: "Perdí la cuenta", pronunciation: "pehr-DEE lah KWEHN-tah" },
        { id: "L32-13", promptEn: "Tell your mom (vos)", targetEs: "Contale a tu mamá", standardEs: "Cuéntale a tu mamá", pronunciation: "kohn-TAH-leh ah too mah-MAH" },
      ],
    },
    {
      id: "L33", title: "Dar", subtitle: "The Powerhouse Verb", icon: "🤲",
      description: "Realizing, not caring, embarrassment — the many idioms of 'dar'", estimatedMinutes: 15,
      dialogue: {
        context: "A friend locks the keys inside the car.",
        lines: [
          { speaker: "A", textEs: "Me di cuenta que dejé las llaves adentro.", textEn: "I realized I left the keys inside." },
          { speaker: "B", textEs: "¡Ay, no! ¿Y ahora?", textEn: "Oh no! Now what?" },
          { speaker: "A", textEs: "Me da igual, llamo al cerrajero. Pero me da pena molestarte.", textEn: "I don't mind, I'll call the locksmith. But I feel bad bothering you." },
          { speaker: "B", textEs: "¡Qué más da! Para eso estamos. Vamos a dar una vuelta mientras.", textEn: "Who cares! That's what we're here for. Let's go for a walk meanwhile." },
        ],
      },
      priorReview: [
        { id: "L21-09", promptEn: "It turns out that...", targetEs: "Resulta que...", pronunciation: "rreh-SOOL-tah keh" },
        { id: "L32-01", promptEn: "What's up? / What's new? (vos)", targetEs: "¿Qué me contás?", standardEs: "¿Qué me cuentas?", pronunciation: "keh meh kohn-TAHS" },
      ],
      newItems: [
        { id: "L33-01", promptEn: "I realized that...", targetEs: "Me di cuenta que...", pronunciation: "meh dee KWEHN-tah keh", culturalNote: "darse cuenta = to realize. Strict grammar wants 'de que', but spoken SV often drops the 'de'" },
        { id: "L33-02", promptEn: "Do you realize? / See what I mean?", targetEs: "¿Te das cuenta?", pronunciation: "teh dahs KWEHN-tah" },
        { id: "L33-03", promptEn: "I don't mind / Either's fine", targetEs: "Me da igual", pronunciation: "meh dah ee-GWAHL", culturalNote: "Not rude — just 'no preference'" },
        { id: "L33-04", promptEn: "I'm embarrassed / shy", targetEs: "Me da pena", pronunciation: "meh dah PEH-nah", culturalNote: "In Central America 'pena' = embarrassment. (In Spain it means sorrow!)" },
        { id: "L33-05", promptEn: "It scares me", targetEs: "Me da miedo", pronunciation: "meh dah mee-EH-doh" },
        { id: "L33-06", promptEn: "What does it matter? / Who cares?", targetEs: "¿Qué más da?", pronunciation: "keh mahs DAH" },
        { id: "L33-07", promptEn: "to go for a stroll", targetEs: "Dar una vuelta", pronunciation: "dahr OO-nah VWEHL-tah" },
        { id: "L33-08", promptEn: "to find / come across (something)", targetEs: "Dar con algo", pronunciation: "dahr kohn AHL-goh", culturalNote: "'Di con la respuesta' = I hit upon the answer" },
        { id: "L33-09", promptEn: "It's all the same to me", targetEs: "Me da lo mismo", pronunciation: "meh dah loh MEES-moh" },
        { id: "L33-10", promptEn: "Realize it / Wise up (vos)", targetEs: "Date cuenta", pronunciation: "DAH-teh KWEHN-tah", culturalNote: "Vos and tú share this command form: date" },
        { id: "L33-11", promptEn: "to give birth", targetEs: "Dar a luz", pronunciation: "dahr ah LOOS", culturalNote: "Literally 'to give to light'" },
        { id: "L33-12", promptEn: "I got the urge to...", targetEs: "Me dieron ganas de...", pronunciation: "meh dee-EH-rohn GAH-nahs deh" },
        { id: "L33-13", promptEn: "to turn around / flip", targetEs: "Dar la vuelta", pronunciation: "dahr lah VWEHL-tah", culturalNote: "Just the article changes it: 'dar UNA vuelta' (a stroll) vs 'dar LA vuelta' (turn around)" },
        { id: "L33-14", promptEn: "Aren't you ashamed?", targetEs: "¿No te da pena?", pronunciation: "noh teh dah PEH-nah", culturalNote: "Gentle scolding" },
      ],
    },
    {
      id: "L34", title: "Quedar", subtitle: "Stay, Fit, Meet & Remain", icon: "📍",
      description: "From 'where is it' to 'it suits you' to 'let's meet at five'", estimatedMinutes: 15,
      dialogue: {
        context: "Making plans and trying on a shirt at a store.",
        lines: [
          { speaker: "A", textEs: "¿Quedamos a las cinco en el centro?", textEn: "Shall we meet at five downtown?" },
          { speaker: "B", textEs: "Dale. ¿Dónde queda la tienda esa?", textEn: "Sure. Where's that store?" },
          { speaker: "A", textEs: "Cerca del parque. Te queda bien esa camisa, por cierto.", textEn: "Near the park. That shirt suits you, by the way." },
          { speaker: "B", textEs: "Gracias. Me quedo con esta, entonces.", textEn: "Thanks. I'll take this one, then." },
        ],
      },
      priorReview: [
        { id: "L04-02", promptEn: "Where is...?", targetEs: "¿Dónde queda...?", pronunciation: "DOHN-deh KEH-dah", culturalNote: "'Quedar' is used more than 'estar' for fixed locations in SV" },
        { id: "L33-03", promptEn: "I don't mind / Either's fine", targetEs: "Me da igual", pronunciation: "meh dah ee-GWAHL" },
      ],
      newItems: [
        { id: "L34-01", promptEn: "Shall we meet at five?", targetEs: "¿Quedamos a las cinco?", pronunciation: "keh-DAH-mohs ah lahs SEEN-koh", culturalNote: "quedar (no -se) = to agree to meet up" },
        { id: "L34-02", promptEn: "It fits / suits me", targetEs: "Me queda bien", pronunciation: "meh KEH-dah bee-EHN" },
        { id: "L34-03", promptEn: "It's too big on me", targetEs: "Me queda grande", pronunciation: "meh KEH-dah GRAHN-deh", culturalNote: "Also figurative: a job or role 'too big' for someone" },
        { id: "L34-04", promptEn: "Where is...? (location)", targetEs: "¿Dónde queda?", pronunciation: "DOHN-deh KEH-dah", culturalNote: "Callback to Pack 01 — quedar for where something sits" },
        { id: "L34-05", promptEn: "I'm staying here", targetEs: "Me quedo aquí", pronunciation: "meh KEH-doh ah-KEE", culturalNote: "quedarse = to stay / remain" },
        { id: "L34-06", promptEn: "I ran out of battery", targetEs: "Quedé sin batería", pronunciation: "keh-DEH seen bah-teh-REE-ah", culturalNote: "quedar sin = to be left without" },
        { id: "L34-07", promptEn: "So what did we decide?", targetEs: "¿En qué quedamos?", pronunciation: "ehn keh keh-DAH-mohs", culturalNote: "Pins down a wishy-washy plan" },
        { id: "L34-08", promptEn: "Stay calm / Chill (vos)", targetEs: "Quedate tranquilo", standardEs: "Quédate tranquilo", pronunciation: "keh-DAH-teh trahn-KEE-loh" },
        { id: "L34-09", promptEn: "The power went out on us", targetEs: "Nos quedamos sin luz", pronunciation: "nohs keh-DAH-mohs seen LOOS" },
        { id: "L34-10", promptEn: "It's clear / understood", targetEs: "Quedó claro", pronunciation: "keh-DOH KLAH-roh" },
        { id: "L34-11", promptEn: "I fell asleep", targetEs: "Me quedé dormido", pronunciation: "meh keh-DEH dohr-MEE-doh" },
        { id: "L34-12", promptEn: "to let someone down / look bad", targetEs: "Quedar mal", pronunciation: "keh-DAHR MAHL", culturalNote: "'Quedé mal con ella' = I let her down / made a bad impression" },
        { id: "L34-13", promptEn: "I'll take / keep this one", targetEs: "Me quedo con esta", pronunciation: "meh KEH-doh kohn EHS-tah" },
        { id: "L34-14", promptEn: "Is it far for you?", targetEs: "¿Te queda lejos?", pronunciation: "teh KEH-dah LEH-hohs" },
      ],
    },
    {
      id: "L35", title: "El se sin culpa", subtitle: "It's Not My Fault", icon: "🤷",
      description: "The construction that turns accidents into nobody's fault", estimatedMinutes: 14,
      dialogue: {
        context: "Someone breaks a mug while helping in the kitchen.",
        lines: [
          { speaker: "A", textEs: "Perdón, se me cayó tu taza y se rompió.", textEn: "Sorry, I dropped your mug and it broke." },
          { speaker: "B", textEs: "No te preocupés, son cosas que pasan.", textEn: "Don't worry, these things happen." },
          { speaker: "A", textEs: "Es que se me hizo tarde y andaba apurada.", textEn: "It's that I ran late and was rushing." },
          { speaker: "B", textEs: "Tranquila. Además, se me olvidó que ya tenía otra.", textEn: "Relax. Besides, I forgot I already had another." },
        ],
      },
      priorReview: [
        { id: "L34-06", promptEn: "I ran out of battery", targetEs: "Quedé sin batería", pronunciation: "keh-DEH seen bah-teh-REE-ah" },
        { id: "L33-04", promptEn: "I'm embarrassed / shy", targetEs: "Me da pena", pronunciation: "meh dah PEH-nah" },
      ],
      newItems: [
        { id: "L35-01", promptEn: "I forgot", targetEs: "Se me olvidó", pronunciation: "seh meh ohl-vee-DOH", culturalNote: "The no-fault 'se' — literally 'it forgot itself on me.' Blame lands on no one" },
        { id: "L35-02", promptEn: "I dropped it", targetEs: "Se me cayó", pronunciation: "seh meh kah-YOH", culturalNote: "'It fell from me' — the object is the subject (cayó is 3rd person), you're just the victim" },
        { id: "L35-03", promptEn: "It broke (on me)", targetEs: "Se me rompió", pronunciation: "seh meh rrohm-pee-OH" },
        { id: "L35-04", promptEn: "I lost track of time / ran late", targetEs: "Se me hizo tarde", pronunciation: "seh meh EE-soh TAHR-deh" },
        { id: "L35-05", promptEn: "I lost it", targetEs: "Se me perdió", pronunciation: "seh meh pehr-dee-OH" },
        { id: "L35-06", promptEn: "I forgot the keys", targetEs: "Se me olvidaron las llaves", pronunciation: "seh meh ohl-vee-DAH-rohn lahs YAH-vehs", culturalNote: "Plural thing (llaves) → verb goes plural: olvidaron" },
        { id: "L35-07", promptEn: "We ran out of coffee", targetEs: "Se nos acabó el café", pronunciation: "seh nohs ah-kah-BOH ehl kah-FEH", culturalNote: "'nos' = it happened to us" },
        { id: "L35-08", promptEn: "You dropped this", targetEs: "Se te cayó esto", pronunciation: "seh teh kah-YOH EHS-toh", culturalNote: "Handy when someone drops something in front of you" },
        { id: "L35-09", promptEn: "He/she burned the food", targetEs: "Se le quemó la comida", pronunciation: "seh leh keh-MOH lah koh-MEE-dah" },
        { id: "L35-10", promptEn: "I missed the bus", targetEs: "Se me fue el bus", pronunciation: "seh meh fweh ehl BOOS", culturalNote: "'The bus left on me'" },
        { id: "L35-11", promptEn: "I find it hard", targetEs: "Se me hace difícil", pronunciation: "seh meh AH-seh dee-FEE-seel" },
        { id: "L35-12", promptEn: "I'm craving a pupusa", targetEs: "Se me antoja una pupusa", pronunciation: "seh meh ahn-TOH-hah OO-nah poo-POO-sah", culturalNote: "antojarse = to feel a craving — same no-fault shape" },
        { id: "L35-13", promptEn: "Can I get you anything?", targetEs: "¿Se te ofrece algo?", pronunciation: "seh teh oh-FREH-seh AHL-goh", culturalNote: "Polite shop/host phrase built on the same structure" },
      ],
    },
    {
      id: "L36", title: "Por y Para", subtitle: "Two Roads", icon: "↔️",
      description: "When to use por and when to use para — finally clear", estimatedMinutes: 15,
      dialogue: {
        context: "Handing over a birthday gift you picked up after work.",
        lines: [
          { speaker: "A", textEs: "Compré esto para vos, por tu cumpleaños.", textEn: "I bought this for you, for your birthday." },
          { speaker: "B", textEs: "¡Gracias por acordarte!", textEn: "Thanks for remembering!" },
          { speaker: "A", textEs: "Pasé por la tienda saliendo del trabajo.", textEn: "I stopped by the store on my way out of work." },
          { speaker: "B", textEs: "Sos un amor. Esto es perfecto para la oficina.", textEn: "You're a sweetheart. This is perfect for the office." },
        ],
      },
      priorReview: [
        { id: "L33-01", promptEn: "I realized that...", targetEs: "Me di cuenta que...", pronunciation: "meh dee KWEHN-tah keh" },
        { id: "L35-04", promptEn: "I lost track of time / ran late", targetEs: "Se me hizo tarde", pronunciation: "seh meh EE-soh TAHR-deh" },
      ],
      newItems: [
        { id: "L36-01", promptEn: "thanks for everything", targetEs: "Gracias por todo", pronunciation: "GRAH-see-ahs pohr TOH-doh", culturalNote: "POR = the reason/cause behind the thanks" },
        { id: "L36-02", promptEn: "I study (in order) to learn", targetEs: "Estudio para aprender", pronunciation: "ehs-TOO-dee-oh PAH-rah ah-prehn-DEHR", culturalNote: "PARA = purpose / goal — the arrow points forward" },
        { id: "L36-03", promptEn: "it's for you (vos)", targetEs: "Es para vos", standardEs: "Es para ti", pronunciation: "ehs PAH-rah vohs", culturalNote: "PARA = recipient / destination" },
        { id: "L36-04", promptEn: "I did it for (because of) you", targetEs: "Lo hice por vos", standardEs: "Lo hice por ti", pronunciation: "loh EE-seh pohr vohs", culturalNote: "POR = motivation — 'for your sake,' not handing you an object" },
        { id: "L36-05", promptEn: "in the morning", targetEs: "Por la mañana", pronunciation: "pohr lah mah-NYAH-nah", culturalNote: "POR = an approximate stretch of time" },
        { id: "L36-06", promptEn: "by tomorrow (deadline)", targetEs: "Para mañana", pronunciation: "PAH-rah mah-NYAH-nah", culturalNote: "PARA = a deadline. Compare 'por la mañana' (when) vs 'para mañana' (due by)" },
        { id: "L36-07", promptEn: "I passed by the house", targetEs: "Pasé por la casa", pronunciation: "pah-SEH pohr lah KAH-sah", culturalNote: "POR = movement through / along / by" },
        { id: "L36-08", promptEn: "I'm heading off to the house", targetEs: "Salgo para la casa", pronunciation: "SAHL-goh PAH-rah lah KAH-sah", culturalNote: "PARA = destination you're aimed at" },
        { id: "L36-09", promptEn: "two for one", targetEs: "Dos por uno", pronunciation: "dohs pohr OO-noh", culturalNote: "POR = exchange / rate" },
        { id: "L36-10", promptEn: "I work for a company", targetEs: "Trabajo para una empresa", pronunciation: "trah-BAH-hoh PAH-rah OO-nah ehm-PREH-sah" },
        { id: "L36-11", promptEn: "please", targetEs: "Por favor", pronunciation: "pohr fah-VOHR", culturalNote: "Even 'please' hides a POR — you're asking 'for a favor'" },
        { id: "L36-12", promptEn: "I'm about to leave", targetEs: "Estoy por salir", pronunciation: "ehs-TOY pohr sah-LEER", culturalNote: "estar por + verb = on the verge of doing it" },
        { id: "L36-13", promptEn: "for me / in my view, it's fine", targetEs: "Para mí, está bien", pronunciation: "PAH-rah MEE ehs-TAH bee-EHN", culturalNote: "PARA = in someone's opinion" },
        { id: "L36-14", promptEn: "thanks for coming", targetEs: "Gracias por venir", pronunciation: "GRAH-see-ahs pohr veh-NEER" },
      ],
    },
    {
      id: "L37", title: "Ojalá", subtitle: "Wishes & the Subjunctive", icon: "🙏",
      description: "Hopes, doubts, and 'when you arrive' — the subjunctive with vos", estimatedMinutes: 15,
      dialogue: {
        context: "Wishing a friend luck the night before an exam.",
        lines: [
          { speaker: "A", textEs: "Mañana tengo el examen. Ojalá me vaya bien.", textEn: "Tomorrow I have the exam. Hopefully it goes well." },
          { speaker: "B", textEs: "Vas a estar bien. Cuando terminés, me avisás.", textEn: "You'll be fine. When you finish, let me know." },
          { speaker: "A", textEs: "Gracias. Espero que tengás razón.", textEn: "Thanks. I hope you're right." },
          { speaker: "B", textEs: "Ojalá que sí. ¡Suerte, maje!", textEn: "Hopefully so. Good luck, dude!" },
        ],
      },
      priorReview: [
        { id: "L36-02", promptEn: "I study (in order) to learn", targetEs: "Estudio para aprender", pronunciation: "ehs-TOO-dee-oh PAH-rah ah-prehn-DEHR" },
        { id: "L33-01", promptEn: "I realized that...", targetEs: "Me di cuenta que...", pronunciation: "meh dee KWEHN-tah keh" },
      ],
      newItems: [
        { id: "L37-01", promptEn: "I hope you come (vos)", targetEs: "Ojalá que vengás", standardEs: "Ojalá vengas", pronunciation: "oh-hah-LAH keh vehn-GAHS", culturalNote: "'Ojalá' (from Arabic 'in shaa Allah') ALWAYS triggers the subjunctive. Voseo: vengás, not vengas" },
        { id: "L37-02", promptEn: "I hope it goes well for you", targetEs: "Espero que te vaya bien", pronunciation: "ehs-PEH-roh keh teh VAH-yah bee-EHN", culturalNote: "esperar que + subjunctive (vaya, not va)" },
        { id: "L37-03", promptEn: "when you arrive, let me know (vos)", targetEs: "Cuando llegués, avisá", standardEs: "Cuando llegues, avisa", pronunciation: "KWAHN-doh yeh-GEHS ah-vee-SAH", culturalNote: "A future 'when' takes the subjunctive — the arrival hasn't happened yet" },
        { id: "L37-04", promptEn: "I don't think it's true", targetEs: "No creo que sea cierto", pronunciation: "noh KREH-oh keh SEH-ah see-EHR-toh", culturalNote: "Doubt / negation → subjunctive (sea, not es)" },
        { id: "L37-05", promptEn: "hopefully so", targetEs: "Ojalá que sí", pronunciation: "oh-hah-LAH keh SEE" },
        { id: "L37-06", promptEn: "I want you to know (vos)", targetEs: "Quiero que sepás", standardEs: "Quiero que sepas", pronunciation: "kee-EH-roh keh seh-PAHS", culturalNote: "Wanting someone ELSE to do something → subjunctive" },
        { id: "L37-07", promptEn: "take care / hope it goes well", targetEs: "Que te vaya bien", pronunciation: "keh teh VAH-yah bee-EHN", culturalNote: "A whole farewell that's pure subjunctive" },
        { id: "L37-08", promptEn: "I hope you're right (vos)", targetEs: "Espero que tengás razón", standardEs: "Espero que tengas razón", pronunciation: "ehs-PEH-roh keh tehn-GAHS rrah-SOHN" },
        { id: "L37-09", promptEn: "even if you don't want to", targetEs: "Aunque no quieras", pronunciation: "ah-OON-keh noh kee-EH-rahs", culturalNote: "aunque + subjunctive = a hypothetical 'even if'" },
        { id: "L37-10", promptEn: "hopefully it won't rain", targetEs: "Ojalá no llueva", pronunciation: "oh-hah-LAH noh YWEH-vah" },
        { id: "L37-11", promptEn: "it's better that you rest (vos)", targetEs: "Es mejor que descansés", standardEs: "Es mejor que descanses", pronunciation: "ehs meh-HOHR keh dehs-kahn-SEHS", culturalNote: "Impersonal 'es mejor que' → subjunctive" },
        { id: "L37-12", promptEn: "when you can, call me (vos)", targetEs: "Cuando puedás, llamame", standardEs: "Cuando puedas, llámame", pronunciation: "KWAHN-doh pweh-DAHS YAH-mah-meh" },
        { id: "L37-13", promptEn: "I doubt he'll come", targetEs: "Dudo que venga", pronunciation: "DOO-doh keh VEHN-gah" },
        { id: "L37-14", promptEn: "so that you understand (vos)", targetEs: "Para que entendás", standardEs: "Para que entiendas", pronunciation: "PAH-rah keh ehn-tehn-DAHS", culturalNote: "'para que' (purpose with a different subject) → subjunctive" },
      ],
    },
    {
      id: "L38", title: "El narrador", subtitle: "A Story, One Line at a Time", icon: "📖",
      description: "Tell a whole folktale sentence by sentence — past tenses in action", estimatedMinutes: 16,
      dialogue: {
        context: "A grandmother begins a bedtime story.",
        lines: [
          { speaker: "A", textEs: "¿Querés que te cuente un cuento?", textEn: "Want me to tell you a story?" },
          { speaker: "B", textEs: "¡Sí, abuela! Contame uno.", textEn: "Yes, grandma! Tell me one." },
          { speaker: "A", textEs: "Bueno... Había una vez, en un pueblo junto al mar...", textEn: "Well... Once upon a time, in a town by the sea..." },
          { speaker: "B", textEs: "¿Y qué pasó?", textEn: "And what happened?" },
        ],
      },
      priorReview: [
        { id: "L32-02", promptEn: "Let me tell you that...", targetEs: "Te cuento que...", pronunciation: "teh KWEHN-toh keh" },
        { id: "L32-13", promptEn: "Tell your mom (vos)", targetEs: "Contale a tu mamá", standardEs: "Cuéntale a tu mamá", pronunciation: "kohn-TAH-leh ah too mah-MAH" },
      ],
      newItems: [
        { id: "L38-01", promptEn: "Once there was a fisherman", targetEs: "Había una vez un pescador", pronunciation: "ah-BEE-ah OO-nah vehs oon pehs-kah-DOHR", culturalNote: "'Había una vez' = 'once upon a time.' Había is imperfect — the timeless story-frame" },
        { id: "L38-02", promptEn: "He lived alone in a little blue house", targetEs: "Vivía solo en una casita azul", pronunciation: "vee-VEE-ah SOH-loh ehn OO-nah kah-SEE-tah ah-SOOL", culturalNote: "Imperfect (vivía) paints ongoing background — no clear start or end" },
        { id: "L38-03", promptEn: "Every morning he'd head out to sea", targetEs: "Todas las mañanas salía al mar", pronunciation: "TOH-dahs lahs mah-NYAH-nahs sah-LEE-ah ahl MAHR", culturalNote: "Imperfect for a repeated habit — 'would' / 'used to'" },
        { id: "L38-04", promptEn: "One day, something changed", targetEs: "Un día, algo cambió", pronunciation: "oon DEE-ah AHL-goh kahm-bee-OH", culturalNote: "Preterite (cambió) snaps in — one completed event that moves the plot" },
        { id: "L38-05", promptEn: "He found a golden fish", targetEs: "Encontró un pez dorado", pronunciation: "ehn-kohn-TROH oon pehs doh-RAH-doh" },
        { id: "L38-06", promptEn: "The fish spoke to him", targetEs: "El pez le habló", pronunciation: "ehl pehs leh ah-BLOH" },
        { id: "L38-07", promptEn: "\"Don't eat me,\" it said to him (vos)", targetEs: "No me comás, le dijo", standardEs: "No me comas, le dijo", pronunciation: "noh meh koh-MAHS leh DEE-hoh", culturalNote: "Dialogue inside the tale — a voseo command plus the preterite 'dijo'" },
        { id: "L38-08", promptEn: "The fisherman got scared", targetEs: "El pescador se asustó", pronunciation: "ehl pehs-kah-DOHR seh ah-soos-TOH", culturalNote: "Preterite for the sudden reaction" },
        { id: "L38-09", promptEn: "But he had a good heart", targetEs: "Pero tenía buen corazón", pronunciation: "PEH-roh teh-NEE-ah bwehn koh-rah-SOHN", culturalNote: "Back to imperfect — describing how he WAS, not a single action" },
        { id: "L38-10", promptEn: "So he set it free", targetEs: "Así que lo dejó libre", pronunciation: "ah-SEE keh loh deh-HOH LEE-breh" },
        { id: "L38-11", promptEn: "From then on, he had luck", targetEs: "Desde entonces, tuvo suerte", pronunciation: "DEHS-deh ehn-TOHN-sehs TOO-voh SWEHR-teh", culturalNote: "'Desde entonces' marks the turning point of the story" },
        { id: "L38-12", promptEn: "He never went hungry again", targetEs: "Nunca más pasó hambre", pronunciation: "NOON-kah mahs pah-SOH AHM-breh" },
        { id: "L38-13", promptEn: "And snip, snap, snout...", targetEs: "Y colorín colorado...", pronunciation: "ee koh-loh-REEN koh-loh-RAH-doh", culturalNote: "The classic rhyming wind-up to a Spanish story" },
        { id: "L38-14", promptEn: "...this tale is done", targetEs: "...este cuento se ha acabado", pronunciation: "EHS-teh KWEHN-toh seh ah ah-kah-BAH-doh", culturalNote: "The closing line every Spanish-speaking kid grows up hearing" },
      ],
    },
    {
      id: "L39", title: "Falsos amigos", subtitle: "Don't Say That!", icon: "⚠️",
      description: "Near-twins and false friends that get embarrassing — handle with care", estimatedMinutes: 15,
      dialogue: {
        context: "A learner makes a classic slip; a friend gently corrects.",
        lines: [
          { speaker: "A", textEs: "Uf, qué calor. Estoy muy caliente.", textEn: "Ugh, so hot. I'm very... aroused." },
          { speaker: "B", textEs: "¡Jaja! Querés decir 'tengo calor'. 'Caliente' es otra cosa.", textEn: "Haha! You mean 'tengo calor.' 'Caliente' is something else." },
          { speaker: "A", textEs: "¡Ay, qué pena!", textEn: "Oh, how embarrassing!" },
          { speaker: "B", textEs: "Tranquilo, a todos nos pasa. Para eso aprendemos.", textEn: "Relax, it happens to everyone. That's how we learn." },
        ],
      },
      priorReview: [
        { id: "L33-04", promptEn: "I'm embarrassed / shy", targetEs: "Me da pena", pronunciation: "meh dah PEH-nah" },
        { id: "L33-14", promptEn: "Aren't you ashamed?", targetEs: "¿No te da pena?", pronunciation: "noh teh dah PEH-nah" },
      ],
      newItems: [
        { id: "L39-01", promptEn: "I'm hot (temperature)", targetEs: "Tengo calor", pronunciation: "TEHN-goh kah-LOHR", culturalNote: "ALWAYS use 'tener calor' for weather or body heat" },
        { id: "L39-02", promptEn: "⚠️ I'm aroused (NOT 'I'm hot')", targetEs: "Estoy caliente", pronunciation: "ehs-TOY kah-lee-EHN-teh", culturalNote: "The classic trap. Calling yourself 'caliente' means sexually aroused — say 'tengo calor' for temperature" },
        { id: "L39-03", promptEn: "the year", targetEs: "el año", pronunciation: "ehl AH-nyoh", culturalNote: "The ñ is everything here" },
        { id: "L39-04", promptEn: "⚠️ the anus", targetEs: "el ano", pronunciation: "ehl AH-noh", culturalNote: "Drop the tilde and 'feliz año' (happy year) becomes something else entirely. The ñ is non-negotiable" },
        { id: "L39-05", promptEn: "but", targetEs: "pero", pronunciation: "PEH-roh", culturalNote: "Single tapped r" },
        { id: "L39-06", promptEn: "the dog", targetEs: "el perro", pronunciation: "ehl PEH-rroh", culturalNote: "Rolled double-rr. 'Pero' (but) vs 'perro' (dog) hangs entirely on that trill" },
        { id: "L39-07", promptEn: "I'm embarrassed", targetEs: "Estoy avergonzado/a", pronunciation: "ehs-TOY ah-vehr-gohn-SAH-doh", culturalNote: "THIS is how you say 'embarrassed'" },
        { id: "L39-08", promptEn: "⚠️ I'm pregnant (NOT embarrassed)", targetEs: "Estoy embarazada", pronunciation: "ehs-TOY ehm-bah-rah-SAH-dah", culturalNote: "The most famous false friend — 'embarazada' = pregnant, never embarrassed" },
        { id: "L39-09", promptEn: "I have a cold", targetEs: "Estoy resfriado/a", pronunciation: "ehs-TOY rrehs-free-AH-doh", culturalNote: "In SV you'll also hear 'estoy agripado/a'" },
        { id: "L39-10", promptEn: "⚠️ I'm congested / have a cold (NOT constipated)", targetEs: "Estoy constipado", pronunciation: "ehs-TOY kohns-tee-PAH-doh", culturalNote: "It means a head cold — not the bowel kind" },
        { id: "L39-11", promptEn: "the potato", targetEs: "la papa", pronunciation: "lah PAH-pah", culturalNote: "Lowercase, feminine" },
        { id: "L39-12", promptEn: "dad", targetEs: "el papá", pronunciation: "ehl pah-PAH", culturalNote: "Stress the last syllable. 'La papa' (potato), 'el papá' (dad), 'el Papa' (the Pope) — accent and article decide" },
        { id: "L39-13", promptEn: "it matters to me", targetEs: "Me importa", pronunciation: "meh eem-POHR-tah" },
        { id: "L39-14", promptEn: "⚠️ I'm aroused (NOT just 'excited')", targetEs: "Estoy excitado", pronunciation: "ehs-TOY ehk-see-TAH-doh", culturalNote: "For plain 'excited,' say 'estoy emocionado/a'" },
      ],
    },
    {
      id: "L40", title: "¿Me regalás...?", subtitle: "The Art of the Soft Ask", icon: "🎁",
      description: "Central American politeness — gifting, diminutives, and gentle requests", estimatedMinutes: 14,
      dialogue: {
        context: "Ordering politely at a small comedor.",
        lines: [
          { speaker: "A", textEs: "Buenas, ¿me regala un vaso de agua, por fa?", textEn: "Hi, could I get a glass of water, please?" },
          { speaker: "B", textEs: "¡Claro! ¿Le sirvo algo más?", textEn: "Of course! Anything else?" },
          { speaker: "A", textEs: "Fíjese que sí — ¿me regala la cuenta también?", textEn: "Actually yes — could you bring the check too?" },
          { speaker: "B", textEs: "Con gusto. Ahorita se la traigo.", textEn: "Gladly. I'll bring it right away." },
        ],
      },
      priorReview: [
        { id: "L21-11", promptEn: "Listen, here's the thing...", targetEs: "Fíjate que...", standardEs: "Fíjate que...", pronunciation: "FEE-hah-teh keh", culturalNote: "Salvadoran softener — eases into a request or bad news" },
        { id: "L31-07", promptEn: "But of course! / Don't mention it", targetEs: "No faltaba más", pronunciation: "noh fahl-TAH-bah MAHS" },
      ],
      newItems: [
        { id: "L40-01", promptEn: "Could I get a glass of water? (vos)", targetEs: "¿Me regalás un vaso de agua?", standardEs: "¿Me regalas un vaso de agua?", pronunciation: "meh rreh-gah-LAHS oon VAH-soh deh AH-gwah", culturalNote: "'Regalar' (to gift) softens a request — distinctly Central American. You're not literally asking for a freebie" },
        { id: "L40-02", promptEn: "Could you bring the check? (usted)", targetEs: "¿Me regala la cuenta?", pronunciation: "meh rreh-GAH-lah lah KWEHN-tah", culturalNote: "Usted form — polite with staff and strangers" },
        { id: "L40-03", promptEn: "Could you spare a moment? (vos)", targetEs: "¿Me regalás el tiempo?", standardEs: "¿Me regalas el tiempo?", pronunciation: "meh rreh-gah-LAHS ehl tee-EHM-poh", culturalNote: "Callback to Pack 01 — 'gift me the time'" },
        { id: "L40-04", promptEn: "Could you help me with something? (vos)", targetEs: "¿Me ayudás con algo?", standardEs: "¿Me ayudas con algo?", pronunciation: "meh ah-yoo-DAHS kohn AHL-goh" },
        { id: "L40-05", promptEn: "Could you do me a favor? (vos)", targetEs: "¿Me hacés un favor?", standardEs: "¿Me haces un favor?", pronunciation: "meh ah-SEHS oon fah-VOHR" },
        { id: "L40-06", promptEn: "a tiny favor", targetEs: "Un favorcito", pronunciation: "oon fah-vohr-SEE-toh", culturalNote: "The diminutive '-ito' shrinks the imposition — makes the ask feel lighter" },
        { id: "L40-07", promptEn: "in a little bit / right away", targetEs: "Ahorita", pronunciation: "ah-oh-REE-tah", culturalNote: "Elastic! Can mean 'this second' or 'sometime soon' — tone and context decide" },
        { id: "L40-08", promptEn: "a little while", targetEs: "Un ratito", pronunciation: "oon rrah-TEE-toh" },
        { id: "L40-09", promptEn: "Give me a sec?", targetEs: "¿Me das un momentito?", pronunciation: "meh dahs oon moh-mehn-TEE-toh" },
        { id: "L40-10", promptEn: "if it's not a bother", targetEs: "Si no es molestia", pronunciation: "see noh ehs moh-LEHS-tee-ah" },
        { id: "L40-11", promptEn: "here's the thing... (vos)", targetEs: "Fijate que...", standardEs: "Fíjate que...", pronunciation: "fee-HAH-teh keh", culturalNote: "Callback to Pack 03 — softens a request or awkward news" },
        { id: "L40-12", promptEn: "would you be so kind as to...?", targetEs: "¿Sería tan amable de...?", pronunciation: "seh-REE-ah tahn ah-MAH-bleh deh", culturalNote: "Extra-formal and very courteous" },
        { id: "L40-13", promptEn: "gladly / my pleasure", targetEs: "Con gusto", pronunciation: "kohn GOOS-toh", culturalNote: "The warm way to say yes to a favor" },
        { id: "L40-14", promptEn: "thanks a million", targetEs: "Mil gracias", pronunciation: "meel GRAH-see-ahs" },
      ],
    },
  ];

  window.HABLA_PACKS.push({
    id: "04-dominio",
    name: "A otro nivel",
    icon: "🧠",
    description: "Advanced — versatile verbs, tricky grammar & storytelling",
    lessons: lessons,
    audio: {},
  });
})();
